name: CorePaperTest
version: ${version}
main: dev.redgamer6427a.core.minecraft.paper.testing.PaperTestPlugin
api-version: '26.1.2'
load: STARTUP
authors: [RedGamer6427A]
description: Testing core.minecraft.paper
